# -*- coding: utf-8 -*-
"""Python Basics Assignment - 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qnVjpSwDgnA3zXHQn57jwNeZMMIeJRq1

1. In the below elements which of them are values or an expression? eg:- values can be integer or string and expressions will be mathematical operators.

1)'hello' - value 

2)-87.8 -  value  

3)- - expression 

4) / - expression 

5)+	- expresssion 

6) 6 - value

2. What is the difference between string and variable? 

Ans: String is array that is used for storing text or characters 
Variable is a memory location. The difference between string and variable is - Variable can be used to store value s data types whereas string can store only text or characters.

3. Describe three different data types.

Ans: 1) Integers: Numbers which does not contain any decimals.
"""

a=7
type(a)

"""2) Floats: Numbers containing decimals."""

pi=3.14
type(pi)

"""3) Complex Numbers: These are imaginary."""

a=2+3j
type(a)

"""4.What is an expression made up of? What do all expressions do?

Ans: An expression is a combination of Values and Operators. All expressions evaluate that is reduce to a single value.

5. This assignment statements, like spam = 10. What is the difference between an expression and a statement?

Ans: An expressison evaluates to a single value whereas a statement does not.
"""

#6. After running the following code, what does the variable bacon contain?
bacon = 22
bacon + 1

"""Ans: After running the above code, the initial value is 23, but in the code we have given an increment of +1. As we know in python the variable takes the largest assigned value.

7. What should the values of the following two terms be?
'spam' + 'spamspam'
'spam' * 3
"""

'spam' + 'spamspam'

'spam' * 3

"""Ans: Both expressions evaluates the string 'spamspamspam'

8. Why is eggs a valid variable name while 100 is invalid?

Ans: This is because the variable names cannot start with a number.

9. What three functions can be used to get the integer, floating-point number, or string version of a value?

Ans: The int() is used to evaluate the integer.
The float() is used for evaluating the floating point number.
The str() is used to pass the string.

10. Why does this expression cause an error? How can you fix it?
'I have eaten ' + 99 + ' burritos.'


Ans: The expression causes an error because 99 is an integer and only strings can be concatenated to other strings with + operator.

The correct way is as follows:
"""

'I have eaten ' + str(99) + ' burritos.'