# -*- coding: utf-8 -*-
"""Python Basics Assignment - 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZrK8De3YGP-UEfzgPFzJoTL_ddyijHn

1. What are escape characters, and how do you use them?

Ans: Escape characters represent characters in string values that would otherwise be difficult or impossible to type into code.

2. What do the escape characters n and t stands for?

Ans: n stands for new line. 

t is a tab.

3. What is the way to include backslash characters in a string?

Ans: The \\ escape character will represent a backslash character in a string.

4. The string "Howl's Moving Castle" is a correct value. Why isn't the single quote character in the word Howl's not escaped a problem?

Ans: It is beacause we have used a double quote at the beginning and at end at the end of a string. This does not caused a problem.

5. How do you write a string of newlines if you don't want to use the n character?

Ans: Multiline strings allow you to use newlines in strings without using the \n escape character.

6. What are the values of the given expressions?

'Hello, world!'[1]

'Hello, world!'[0:5]

'Hello, world!'[:5]

'Hello, world!'[3:]
"""

'Hello, world!'[1]

'Hello, world!'[0:5]

'Hello, world!'[:5]

'Hello, world!'[3:]

"""7. What are the values of the following expressions?

'Hello'.upper()

'Hello'.upper().isupper()

'Hello'.upper().lower()

"""

'Hello'.upper()

'Hello'.upper().isupper()

'Hello'.upper().lower()

"""8. What are the values of the following expressions?
'Remember, remember, the fifth of July.'.split()
'-'.join('There can only one.'.split())

"""

'Remember, remember, the fifth of July.'.split()
'-'.join('There can only one.'.split())

"""9. What are the methods for right-justifying, left-justifying, and centering a string?

Ans: rjust( ) is for right-justifying.

ljust() is for left justifying and center() is for centering a string.

10. What is the best way to remove whitespace characters from the start or end?

Ans: The lstrip() and rstrip() are the methods that remove the whitespace characters from thye strat or end.
"""