# -*- coding: utf-8 -*-
"""Python Basics Assignments - 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_FhbqAbPEKNRNWCRmUUK70XGdryrXx-T

1. Is the Python Standard Library included with PyInputPlus?

Ans: No, PyInputPlus is a third party module and it doesnot come with the python standard library.

2. Why is PyInputPlus commonly imported with import pyinputplus as pypi?

Ans: This optinally makes your code shorter to type, you can type pypi.inputStr() instead of pypinutplus.inputStr().

3. How do you distinguish between inputInt() and inputFloat()?

Ans: The inputInt() function returns an int value while inputFloat() function returns a float value. This is the difference between returning 4 and 4.0

4. Using PyInputPlus, how do you ensure that the user enters a whole number between 0 and 99?

Ans: Call pypi.inputint(min=0,max=99)

5. What is transferred to the keyword arguments allowRegexes and blockRegexes?

Ans: A list of regex strings that are either explicitly allowed or denied.

6. If a blank input is entered three times, what does inputStr(limit=3) do?

Ans: The function will raise RetryLimitException.

7. If blank input is entered three times, what does inputStr(limit=3, default='hello') do?

Ans: The function returns the value 'hello'.
"""